export enum Screens {
  MAIN_APP_ROUTE = 'MAIN_APP_ROUTE',

  MAIN_AUTH_ROUTES = 'MAIN_AUTH_ROUTES',

  HOME_APP_SCREEN = 'HOME_APP_SCREEN',

  HOME_SCREEN = 'HOME_SCREEN',

  PROFILE_SCREEN = 'PROFILE_SCREEN',

  WALLET_SCREEN = 'WALLET_SCREEN',

  ITEM_LOBBY_SCREEN = 'ITEM_LOBBY_SCREEN',
}
